In [23]:
import numpy as np
arr=np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
np.random.rand(3,3)

array([[0.37460677, 0.62141583, 0.27319813],
       [0.05305384, 0.16968729, 0.92485909],
       [0.31474226, 0.97622462, 0.44527691]])

In [25]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
np.dot(a,b)

np.int64(130)

In [26]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c.shape)
print(c.ndim)
print(c.dtype)

(3, 3)
2
int64


In [27]:
m=np.arange(12)
print(m)
n=m.reshape(3,4)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
np.max(m),np.min(m)

(np.int64(11), np.int64(0))

In [29]:
a+b

array([ 7,  9, 11, 13, 15])

In [30]:
arr=np.array([12,50,51,58,69,100,152,10,15,26,31,26,15,26,32])
arr[arr>50]

array([ 51,  58,  69, 100, 152])

In [31]:
import pandas as pd
arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(arr,columns=['a','b','c'])
print(df)

   a  b  c
0  1  2  3
1  4  5  6


-------------------------------------------------------------------------------------------------