In [4]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.4 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/12.8 MB 1.1 MB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.8 MB 1.1 MB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.8 MB 886.1 kB/s eta 0:00:14
   ---- ----------------------------------- 1.3/12.8 MB 965.0 kB/s eta 0:00:12
   ---- ----------------------------------- 1.6/12.8 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.6/12.8 MB 1.0 MB/s eta 0:00:12
   ----- ---------------------------------- 1.8/12.8 MB 928.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.8/12.8 MB 928.3 kB/s eta 0:00:12
   ------ ---------

In [93]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [7]:
import numpy as np
a=np.arange(0,22,3).reshape(4,2)
print(a)

[[ 0  3]
 [ 6  9]
 [12 15]
 [18 21]]


In [14]:
b=np.array([[[1,5,2,3,6]]])
print(b)
print(b.ndim)

[[[1 5 2 3 6]]]
3


In [91]:
a=np.array([10,20,30,40,50,60,70])
print(a[-1:-5:-1])
print(np.sqrt(a))
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))
print(np.sum(a))
print(max(a))
print(min(a))
print(np.cumsum(a))
print(np.cumprod(a))

[70 60 50 40]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027]
40.0
40.0
400.0
20.0
280
70
10
[ 10  30  60 100 150 210 280]
[         10         200        6000      240000    12000000   720000000
 50400000000]


In [67]:
a=np.array([10,20,30,40,50,60,70,80])
b=np.array([11,12,13,14,15,16,17,18])
print(np.concatenate((a,b)))
print(np.stack((a,b),axis=0))
print(np.stack((a,b),axis=1))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[10 20 30 40 50 60 70 80 11 12 13 14 15 16 17 18]
[[10 20 30 40 50 60 70 80]
 [11 12 13 14 15 16 17 18]]
[[10 11]
 [20 12]
 [30 13]
 [40 14]
 [50 15]
 [60 16]
 [70 17]
 [80 18]]
[[10 20 30 40 50 60 70 80]
 [11 12 13 14 15 16 17 18]]
[10 20 30 40 50 60 70 80 11 12 13 14 15 16 17 18]


In [73]:
b=a.reshape(2,4)
print(b)
print(np.transpose(b))

[[10 20 30 40]
 [50 60 70 80]]
[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [80]:
b=a.reshape(2,4)
print(b)
print(np.split(b,2))
print(np.hsplit(b,2))
print(np.vsplit(b,2))

[[10 20 30 40]
 [50 60 70 80]]
[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]])]
[array([[10, 20],
       [50, 60]]), array([[30, 40],
       [70, 80]])]
[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]])]


In [83]:
c=np.array([1,2,3,4])
print(np.repeat(c,2))
print(np.tile(c,2))

[1 1 2 2 3 3 4 4]
[1 2 3 4 1 2 3 4]


In [92]:
def square (x):
    return x*x
v=np.vectorize(square)
a=np.array([1,2,3,4,5])
print(v(a))

[ 1  4  9 16 25]
