In [127]:
import pandas as pd
df=pd.read_csv(r"c:\DATA SCIENCE\Machine_Learning\Datasets\Churn_Modelling (1) (2).csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female   NaN   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female   NaN   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [128]:
df.shape

(10000, 14)

In [129]:
df.duplicated().sum()

np.int64(0)

In [130]:
df.isnull().sum()

RowNumber           0
CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender             30
Age                32
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember      0
EstimatedSalary     0
Exited              0
dtype: int64

In [131]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [132]:
df.columns=df.columns.str.lower()

In [133]:
num_cols=df.select_dtypes(include=["int","float"])
cat_cols=df.select_dtypes(include=["object"])

In [134]:
df.columns

Index(['rownumber', 'customerid', 'surname', 'creditscore', 'geography',
       'gender', 'age', 'tenure', 'balance', 'numofproducts', 'hascrcard',
       'isactivemember', 'estimatedsalary', 'exited'],
      dtype='object')

In [135]:
df.drop(['rownumber', 'customerid', 'surname'],inplace=True,axis=1)

In [136]:
df.dtypes

creditscore          int64
geography           object
gender              object
age                float64
tenure               int64
balance            float64
numofproducts        int64
hascrcard            int64
isactivemember       int64
estimatedsalary    float64
exited               int64
dtype: object

In [137]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["gender"]=encoder.fit_transform(df["gender"])

In [138]:
df.tail()

creditscore geography  gender   age  tenure    balance  numofproducts  \
9995          771    France       1   NaN       5       0.00              2   
9996          516    France       1  35.0      10   57369.61              1   
9997          709    France       0  36.0       7       0.00              1   
9998          772   Germany       1  42.0       3   75075.31              2   
9999          792    France       0  28.0       4  130142.79              1   

      hascrcard  isactivemember  estimatedsalary  exited  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0

In [139]:
import pickle
with open("labelencoder.pkl","wb") as file:
    pickle.dump(encoder,file)

In [140]:
from sklearn.preprocessing import OneHotEncoder
df_geo = pd.DataFrame({ "geography": ["France", "Spain", "Germany"] })
ohe=OneHotEncoder(sparse_output=False)
geo_encoder=ohe.fit_transform(df[["geography"]])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [141]:
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(ohe,file)

In [142]:
ohe.get_feature_names_out(['geography'])

array(['geography_France', 'geography_Germany', 'geography_Spain'],
      dtype=object)

In [143]:
geo_df=pd.DataFrame(geo_encoder,columns=ohe.get_feature_names_out(['geography']))
geo_df

geography_France  geography_Germany  geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [144]:
df.drop("geography",inplace=True,axis=1)

In [145]:
df.head()

creditscore  gender   age  tenure    balance  numofproducts  hascrcard  \
0          619       0  42.0       2       0.00              1          1   
1          608       0  41.0       1   83807.86              1          0   
2          502       0   NaN       8  159660.80              3          1   
3          699       0  39.0       1       0.00              2          0   
4          850       0   NaN       2  125510.82              1          1   

   isactivemember  estimatedsalary  exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

In [146]:
new_df=pd.concat([df,geo_df],axis=1)
new_df.dtypes
new_df.head()

creditscore  gender   age  tenure    balance  numofproducts  hascrcard  \
0          619       0  42.0       2       0.00              1          1   
1          608       0  41.0       1   83807.86              1          0   
2          502       0   NaN       8  159660.80              3          1   
3          699       0  39.0       1       0.00              2          0   
4          850       0   NaN       2  125510.82              1          1   

   isactivemember  estimatedsalary  exited  geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   geography_Germany  geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [147]:
x=new_df.drop("exited",axis=1)
y=new_df["exited"]

In [148]:
x

creditscore  gender   age  tenure    balance  numofproducts  hascrcard  \
0             619       0  42.0       2       0.00              1          1   
1             608       0  41.0       1   83807.86              1          0   
2             502       0   NaN       8  159660.80              3          1   
3             699       0  39.0       1       0.00              2          0   
4             850       0   NaN       2  125510.82              1          1   
...           ...     ...   ...     ...        ...            ...        ...   
9995          771       1   NaN       5       0.00              2          1   
9996          516       1  35.0      10   57369.61              1          1   
9997          709       0  36.0       7       0.00              1          0   
9998          772       1  42.0       3   75075.31              2          1   
9999          792       0  28.0       4  130142.79              1          1   

      isactivemember  estimatedsalary  geography_France  geography_Germany  \
0                  1        101348.88               1.0                0.0   
1                  1        112542.58               0.0                0.0   
2                  0        113931.57               1.0                0.0   
3                  0         93826.63               1.0                0.0   
4                  1         79084.10               0.0                0.0   
...              ...              ...               ...                ...   
9995               0         96270.64               1.0                0.0   
9996               1        101699.77               1.0                0.0   
9997               1         42085.58               1.0                0.0   
9998               0         92888.52               0.0                1.0   
9999               0         38190.78               1.0                0.0   

      geography_Spain  
0                 0.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 1.0  
...               ...  
9995              0.0  
9996              0.0  
9997              0.0  
9998              0.0  
9999              0.0  

[10000 rows x 12 columns]

In [149]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: exited, Length: 10000, dtype: int64

In [150]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.8)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8000, 12), (2000, 12), (8000,), (2000,))

ANN model classification

In [151]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
model=Sequential()
#adding layers
model.add(Dense(32, activation='relu', input_dim=x_train.shape[1]))#input layer with relu activaion function with 32 neurons
model.add(Dense(16,activation='relu'))                                    #hidden layer with relu activation function with 16 neurons
model.add(Dense(1,activation='sigmoid'))                                  #output layer with sigmoid activation function with 1 neuron

c:\Users\prasa\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [175]:
with open("model_ann.pkl","wb") as file:
    pickle.dump(model,file)

In [152]:
x_train.shape[1]

12

In [153]:
model.summary()
#13*32+32
#32*16+16

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 961 (3.75 KB)

 Trainable params: 961 (3.75 KB)

 Non-trainable params: 0 (0.00 B)

In [154]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])


In [155]:
history = model.fit(x_train, y_train, epochs=50, batch_size=20, validation_split=0.2, verbose=1)

Epoch 1/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7872 - loss: 13.8059 - val_accuracy: 0.7987 - val_loss: 0.6182
Epoch 2/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5944 - val_accuracy: 0.7987 - val_loss: 0.5699
Epoch 3/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5573 - val_accuracy: 0.7987 - val_loss: 0.5404
Epoch 4/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5352 - val_accuracy: 0.7987 - val_loss: 0.5230
Epoch 5/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5226 - val_accuracy: 0.7987 - val_loss: 0.5130
Epoch 6/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7934 - loss: 0.5158 - val_accuracy: 0.7987 - val_loss: 0.5077
Epoch 7/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5124 - val_accuracy: 0.7987 - val_loss: 0.5049
Epoch 8/50
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.5107 - val_accuracy: 0

In [156]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

<LossFunctionWrapper(<function binary_crossentropy at 0x000002856EAC9760>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [157]:
model.save('model.h5')

In [158]:
y_pred=model.predict(x_test)
print(f"y predicted values are {y_pred[:10]}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
y predicted values are [[0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]
 [0.20692825]]


In [159]:
import numpy as np
from sklearn.metrics import accuracy_score

# If y_pred are probabilities (floats between 0 and 1)
y_pred_labels = (y_pred > 0.5).astype(int)

print(accuracy_score(y_test, y_pred_labels))


0.8035


NEW data 

In [160]:
with open("labelencoder.pkl","rb") as file:
    labelencoder=pickle.load(file)
with open("onehot_encoder_geo.pkl","rb") as file:
    onehot_encoder=pickle.load(file)


In [161]:
new_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Female',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 0,
    'IsActiveMember': 0,
    'EstimatedSalary': 20000
}
new_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Female',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 0,
 'IsActiveMember': 0,
 'EstimatedSalary': 20000}

In [163]:
geo_encoder=onehot_encoder.transform([[new_data["Geography"]]])
geo_encoder


c:\Users\prasa\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [164]:
onehot_encoder.feature_names_in_

array(['geography'], dtype=object)

In [165]:
onehot_encoder.get_feature_names_out(onehot_encoder.feature_names_in_)


array(['geography_France', 'geography_Germany', 'geography_Spain'],
      dtype=object)

In [166]:
new_data=pd.DataFrame([new_data])
new_data


CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France  Female   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          0               0            20000

In [167]:
geo_df=pd.DataFrame(geo_encoder,columns=onehot_encoder.get_feature_names_out(onehot_encoder.feature_names_in_))

In [168]:
geo_df

geography_France  geography_Germany  geography_Spain
0               1.0                0.0              0.0

In [169]:
new_data["Gender"]=labelencoder.transform(new_data["Gender"])
new_data

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       0   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          0               0            20000

In [170]:
input_df=pd.concat([new_data.drop("Geography",axis=1),geo_df],axis=1)
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       0   40       3    60000              2          0   

   IsActiveMember  EstimatedSalary  geography_France  geography_Germany  \
0               0            20000               1.0                0.0   

   geography_Spain  
0              0.0

In [171]:
model.predict(input_df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[0.20692825]], dtype=float32)

In [172]:
prediction=model.predict(input_df)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[0.20692825]], dtype=float32)

In [173]:
prediction_proba = prediction[0][0]
prediction_proba

np.float32(0.20692825)

In [174]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.
